// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(WishlistDbContext))]
    [Migration("20251108194345_AuctionAddedRV")]
    partial class AuctionAddedRV
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.AppListings.AppListing", b =>
                {
                    b.Property<int>("appid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("appid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("appid")
                        .HasName("pk_app_listings");

                    b.HasIndex("appid")
                        .HasDatabaseName("ix_app_listings_appid");

                    b.ToTable("app_listings", (string)null);
                });

            modelBuilder.Entity("DataAccess.Auctions.Auction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("starting_price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("appid")
                        .HasColumnType("integer")
                        .HasColumnName("appid");

                    b.HasKey("ID")
                        .HasName("pk_auctions");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_auctions_user_id");

                    b.HasIndex("appid")
                        .HasDatabaseName("ix_auctions_appid");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("DataAccess.Users.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("ID")
                        .HasName("pk_users");

                    b.HasIndex("UUID")
                        .IsUnique()
                        .HasDatabaseName("ix_users_uuid");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataAccess.Wishlist.WishlistItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("appid")
                        .HasColumnType("integer")
                        .HasColumnName("appid");

                    b.HasKey("ID")
                        .HasName("pk_wishlist_items");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_wishlist_items_user_id");

                    b.HasIndex("appid")
                        .HasDatabaseName("ix_wishlist_items_appid");

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("DataAccess.Auctions.Auction", b =>
                {
                    b.HasOne("DataAccess.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .HasConstraintName("fk_auctions_users_user_id");

                    b.HasOne("DataAccess.AppListings.AppListing", "AppListing")
                        .WithMany()
                        .HasForeignKey("appid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_app_listings_appid");

                    b.Navigation("AppListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Wishlist.WishlistItem", b =>
                {
                    b.HasOne("DataAccess.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_items_users_user_id");

                    b.HasOne("DataAccess.AppListings.AppListing", "AppListing")
                        .WithMany()
                        .HasForeignKey("appid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_items_app_listings_appid");

                    b.Navigation("AppListing");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
