FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /workspace/api
COPY SteamTracker/src/SteamTracker.Worker/SteamTracker.Worker.csproj ./SteamTracker/src/SteamTracker.Worker/
COPY SteamTracker/src/SteamTracker.Application/SteamTracker.Application.csproj ./SteamTracker/src/SteamTracker.Application/
COPY SteamTracker/src/SteamTracker.Domain/SteamTracker.Domain.csproj ./SteamTracker/src/SteamTracker.Domain/
COPY SteamTracker/src/SteamTracker.Infrastructure/SteamTracker.Infrastructure.csproj ./SteamTracker/src/SteamTracker.Infrastructure/
COPY CrossService/CrossService.csproj ./CrossService/
RUN dotnet restore SteamTracker/src/SteamTracker.Worker/SteamTracker.Worker.csproj
