services:
  devc:
    build: 
      context: ./.devcontainer
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sleep infinity

  rabbitmq:
    image: rabbitmq:4.2-management
    restart: on-failure:3
    ports:
      - "15672:15672"  # Management UI

  db:
    image: postgres:18.1
    restart: on-failure:3
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: steamtracker
    volumes:
      - db_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: on-failure:3
    ports:
      - 8085:8080

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: ["5173:5173"]
    volumes:
      - .:/workspace
      - react_node_modules:/workspace/frontend/node_modules  # hides host node_modules
    working_dir: /workspace/frontend
    command: npm run dev -- --host --mode devcontainer
    environment:
      - NODE_ENV=devcontainer

  api:
    build: 
      context: ./api/WishlistApi
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - rabbitmq
      - steamtracker-api
    ports: ["5186:5186"]    
    volumes: 
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace/api/WishlistApi/WishlistApi
    command: dotnet run --no-launch-profile --urls http://0.0.0.0:5186 -- --Logging:LogLevel:Default=Warning
    environment:
      - ASPNETCORE_ENVIRONMENT=Devcontainer
      - ASPNETCORE_URLS=http://+:5186

  steamtracker-api:
    build:
      context: ./api
      dockerfile: SteamTracker/src/SteamTracker.API/Dockerfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - "5217:5217"
    environment:
      - ConnectionStrings__SteamTracker=Host=db;Database=steamtracker;Username=postgres;Password=example
      - RabbitMQ__HostName=rabbitmq
      - ASPNETCORE_URLS=http://+:5217

  steamtracker-worker:
    build: 
      context: ./api
      dockerfile: SteamTracker/src/SteamTracker.Worker/Dockerfile.dev
    depends_on:
      - db
      - rabbitmq
    volumes: 
      - .:/workspace
    working_dir: /workspace/api/SteamTracker/src/SteamTracker.Worker
    command: dotnet run --no-launch-profile -- --Logging:LogLevel:Default=Warning
    environment:
      - ConnectionStrings__SteamTracker=Host=db;Database=steamtracker;Username=postgres;Password=example
      - RabbitMQ__HostName=rabbitmq

volumes:
  db_data:
  react_node_modules:
