# postres, web api, react, reverse proxy

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432 # todo remove for final version
    environment:
      POSTGRES_PASSWORD: example # todo from env var
    volumes:
      - db_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build:
      context: ./api/WishlistApi
    depends_on:
      - db
    container_name: my-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5186

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    environment:
      - NODE_ENV=production

  proxy:
    image: nginx:alpine
    container_name: my-proxy
    ports:
      - "80:80" # Expose Nginx port 80 to the host's port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
