/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppOverviewRouteImport } from './routes/app/overview'
import { Route as AppLiveauctionRouteImport } from './routes/app/liveauction'
import { Route as AppLessonsLearnedRouteImport } from './routes/app/lessonsLearned'
import { Route as AppAuctionRouteImport } from './routes/app/auction'
import { Route as AppAboutRouteImport } from './routes/app/about'
import { Route as AppProfileRouteRouteImport } from './routes/app/profile/route'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppProfileEditRouteImport } from './routes/app/profile/edit'
import { Route as AppAdminProfileRouteRouteImport } from './routes/app/admin/profile/route'
import { Route as AppAdminProfileIndexRouteImport } from './routes/app/admin/profile/index'
import { Route as AppAdminProfileEditRouteImport } from './routes/app/admin/profile/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLiveauctionRoute = AppLiveauctionRouteImport.update({
  id: '/liveauction',
  path: '/liveauction',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLessonsLearnedRoute = AppLessonsLearnedRouteImport.update({
  id: '/lessonsLearned',
  path: '/lessonsLearned',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuctionRoute = AppAuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppAdminProfileRouteRoute = AppAdminProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminProfileIndexRoute = AppAdminProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminProfileRouteRoute,
} as any)
const AppAdminProfileEditRoute = AppAdminProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAdminProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/profile': typeof AppProfileRouteRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/auction': typeof AppAuctionRoute
  '/app/lessonsLearned': typeof AppLessonsLearnedRoute
  '/app/liveauction': typeof AppLiveauctionRoute
  '/app/overview': typeof AppOverviewRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/profile': typeof AppAdminProfileRouteRouteWithChildren
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/admin/profile/edit': typeof AppAdminProfileEditRoute
  '/app/admin/profile/': typeof AppAdminProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/about': typeof AppAboutRoute
  '/app/auction': typeof AppAuctionRoute
  '/app/lessonsLearned': typeof AppLessonsLearnedRoute
  '/app/liveauction': typeof AppLiveauctionRoute
  '/app/overview': typeof AppOverviewRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/admin/profile/edit': typeof AppAdminProfileEditRoute
  '/app/admin/profile': typeof AppAdminProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/profile': typeof AppProfileRouteRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/auction': typeof AppAuctionRoute
  '/app/lessonsLearned': typeof AppLessonsLearnedRoute
  '/app/liveauction': typeof AppLiveauctionRoute
  '/app/overview': typeof AppOverviewRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/profile': typeof AppAdminProfileRouteRouteWithChildren
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/admin/profile/edit': typeof AppAdminProfileEditRoute
  '/app/admin/profile/': typeof AppAdminProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/profile'
    | '/app/about'
    | '/app/auction'
    | '/app/lessonsLearned'
    | '/app/liveauction'
    | '/app/overview'
    | '/auth/login'
    | '/auth/logout'
    | '/app/'
    | '/auth/'
    | '/app/admin/profile'
    | '/app/profile/edit'
    | '/app/admin/'
    | '/app/profile/'
    | '/app/admin/profile/edit'
    | '/app/admin/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/about'
    | '/app/auction'
    | '/app/lessonsLearned'
    | '/app/liveauction'
    | '/app/overview'
    | '/auth/login'
    | '/auth/logout'
    | '/app'
    | '/auth'
    | '/app/profile/edit'
    | '/app/admin'
    | '/app/profile'
    | '/app/admin/profile/edit'
    | '/app/admin/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/profile'
    | '/app/about'
    | '/app/auction'
    | '/app/lessonsLearned'
    | '/app/liveauction'
    | '/app/overview'
    | '/auth/login'
    | '/auth/logout'
    | '/app/'
    | '/auth/'
    | '/app/admin/profile'
    | '/app/profile/edit'
    | '/app/admin/'
    | '/app/profile/'
    | '/app/admin/profile/edit'
    | '/app/admin/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/liveauction': {
      id: '/app/liveauction'
      path: '/liveauction'
      fullPath: '/app/liveauction'
      preLoaderRoute: typeof AppLiveauctionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lessonsLearned': {
      id: '/app/lessonsLearned'
      path: '/lessonsLearned'
      fullPath: '/app/lessonsLearned'
      preLoaderRoute: typeof AppLessonsLearnedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/auction': {
      id: '/app/auction'
      path: '/auction'
      fullPath: '/app/auction'
      preLoaderRoute: typeof AppAuctionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/admin/profile': {
      id: '/app/admin/profile'
      path: '/profile'
      fullPath: '/app/admin/profile'
      preLoaderRoute: typeof AppAdminProfileRouteRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/profile/': {
      id: '/app/admin/profile/'
      path: '/'
      fullPath: '/app/admin/profile/'
      preLoaderRoute: typeof AppAdminProfileIndexRouteImport
      parentRoute: typeof AppAdminProfileRouteRoute
    }
    '/app/admin/profile/edit': {
      id: '/app/admin/profile/edit'
      path: '/edit'
      fullPath: '/app/admin/profile/edit'
      preLoaderRoute: typeof AppAdminProfileEditRouteImport
      parentRoute: typeof AppAdminProfileRouteRoute
    }
  }
}

interface AppAdminProfileRouteRouteChildren {
  AppAdminProfileEditRoute: typeof AppAdminProfileEditRoute
  AppAdminProfileIndexRoute: typeof AppAdminProfileIndexRoute
}

const AppAdminProfileRouteRouteChildren: AppAdminProfileRouteRouteChildren = {
  AppAdminProfileEditRoute: AppAdminProfileEditRoute,
  AppAdminProfileIndexRoute: AppAdminProfileIndexRoute,
}

const AppAdminProfileRouteRouteWithChildren =
  AppAdminProfileRouteRoute._addFileChildren(AppAdminProfileRouteRouteChildren)

interface AppAdminRouteRouteChildren {
  AppAdminProfileRouteRoute: typeof AppAdminProfileRouteRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminProfileRouteRoute: AppAdminProfileRouteRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppProfileRouteRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteRouteChildren: AppProfileRouteRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteRouteWithChildren = AppProfileRouteRoute._addFileChildren(
  AppProfileRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppProfileRouteRoute: typeof AppProfileRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppAuctionRoute: typeof AppAuctionRoute
  AppLessonsLearnedRoute: typeof AppLessonsLearnedRoute
  AppLiveauctionRoute: typeof AppLiveauctionRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppProfileRouteRoute: AppProfileRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppAuctionRoute: AppAuctionRoute,
  AppLessonsLearnedRoute: AppLessonsLearnedRoute,
  AppLiveauctionRoute: AppLiveauctionRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
