// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SteamTracker.Infrastructure.Data;

#nullable disable

namespace SteamTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SteamTrackerDbContext))]
    [Migration("20260711114733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SteamTracker.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("AlertRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_triggered_at");

                    b.Property<string>("TriggerBelowPrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_below_price");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("AlertRuleId")
                        .HasName("pk_alert_rules");

                    b.HasIndex("UserId", "AppId")
                        .HasDatabaseName("ix_alert_rules_user_id_app_id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.Game", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<string>("CurrentPrice")
                        .HasColumnType("text")
                        .HasColumnName("current_price");

                    b.Property<bool>("IsUnavailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unavailable");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("AppId")
                        .HasName("pk_games");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.HasKey("SnapshotId")
                        .HasName("pk_price_snapshots");

                    b.HasIndex("GameId", "CapturedAt")
                        .HasDatabaseName("ix_price_snapshots_game_id_captured_at");

                    b.ToTable("price_snapshots", (string)null);
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.TrackedGame", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("TrackedSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tracked_since");

                    b.HasKey("AppId")
                        .HasName("pk_tracked_games");

                    b.HasIndex("AppId")
                        .HasDatabaseName("ix_tracked_games_app_id");

                    b.ToTable("tracked_games", (string)null);
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("SteamTracker.Domain.Entities.Game", null)
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_snapshots_games_game_id");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.Game", b =>
                {
                    b.Navigation("PriceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
