// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SteamTracker.Infrastructure.Data;

#nullable disable

namespace SteamTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SteamTrackerDbContext))]
    [Migration("20260708000000_AddIsUnavailableToGame")]
    partial class AddIsUnavailableToGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasDefaultSchema("public");

            modelBuilder.Entity("SteamTracker.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ThresholdAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_amount");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("IX_alert_rules_user_id_app_id");

                    b.ToTable("alert_rules");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.Game", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<bool>("IsUnavailable")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("is_unavailable");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.HasKey("AppId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "CreatedAt")
                        .IsUnique()
                        .HasDatabaseName("IX_price_snapshots_app_id_created_at");

                    b.ToTable("price_snapshots");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("SteamTracker.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_snapshots_games_app_id");
                });
#pragma warning restore 612, 618
        }
    }
}
