// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SteamTracker.Infrastructure.Data;

#nullable disable

namespace SteamTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SteamTrackerDbContext))]
    partial class SteamTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SteamTracker.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("AlertRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TriggerBelowPrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("AlertRuleId");

                    b.HasIndex("UserId", "AppId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.Game", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentPrice")
                        .HasColumnType("text");

                    b.Property<decimal?>("CurrentPriceAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("CurrentPriceAmount");

                    b.Property<string>("CurrentPriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("CurrentPriceCurrency");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("AppId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.PriceSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SnapshotId");

                    b.HasIndex("GameId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.TrackedGame", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("TrackedSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId");

                    b.HasIndex("AppId");

                    b.ToTable("TrackedGames");
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.PriceSnapshot", b =>
                {
                    b.HasOne("SteamTracker.Domain.Entities.Game", null)
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamTracker.Domain.Entities.Game", b =>
                {
                    b.Navigation("PriceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
