FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /workspace/api/SteamTracker/src
COPY SteamTracker.Worker/SteamTracker.Worker.csproj ./SteamTracker.Worker/
COPY SteamTracker.Application/SteamTracker.Application.csproj ./SteamTracker.Application/
COPY SteamTracker.Domain/SteamTracker.Domain.csproj ./SteamTracker.Domain/
COPY SteamTracker.Infrastructure/SteamTracker.Infrastructure.csproj ./SteamTracker.Infrastructure/
RUN dotnet restore SteamTracker.Worker/SteamTracker.Worker.csproj
